name = "the-dreaming-scallion-journal"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "journal-db"
database_id = "b4bbb051-1b2e-4a05-84fb-3cbc2968208f"
